### ISSUE TITLE
Hi Sir,

### ISSUE THREAD

**Issue by Oliver0804** [rmptxf/test_project#1]
I get failures when I use your project to recompile.

My segger version is 6.30.

Have you run into the same problem? Thank you

![截圖 2022-06-06 下午7 21 06](https://user-images.githubusercontent.com/8245980/172151345-08cfedef-16d4-4995-a6a6-54ede644a8e2.png)

**Comment by rmptxf** [comment]
Hi,
Please try with an older version, for example the 5.66.

Hope that helps
Abdelali

**Comment by Oliver0804** [comment]
Really thank you for your reply and solved for now.
